repos:
-   repo: local
    hooks:
    -   id: format
        name: 'Formatting Code'
        entry: 'make format'
        language: system
        pass_filenames: false
    -   id: verify
        name: 'Static Analysis'
        entry: 'make verify'
        language: system
        pass_filenames: false
    -   id: unit-tests
        name: 'Unit Tests'
        entry: 'make unit-test'
        language: system
        pass_filenames: false
    -   id: acceptance-tests
        name: 'Acceptance Tests'
        entry: 'make acceptance-test'
        language: system
        pass_filenames: false