#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - apt-get -y update
            - apt-get -y install sqlite3
            - python -m venv .venv/
            - source .venv/bin/activate
            - python -m pip install --upgrade pip
            - ls -l
            - ls -la tests/data
            - pwd
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pip install pytest
            - SQLITE_DB_FILE="$(pwd)/tests/data/test_data.db"
            - pytest -v tests/*_test.py  --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics