import os

# Alpaca paper trading and marked data API
ALPACA_PAPER_API_KEY = os.getenv("ALPACA_PAPER_API_KEY")
ALPACA_PAPER_SECRET = os.getenv("ALPACA_PAPER_SECRET")
ALPACA_PAPER_API_KEY_2 = os.getenv("ALPACA_PAPER_API_KEY_2")
ALPACA_PAPER_SECRET_2 = os.getenv("ALPACA_PAPER_SECRET_2")
ALPACA_PAPER_TRADING_REST_ENDPOINT = "https://paper-api.alpaca.markets"

# Alpaca live trading and marked data API
ALPACA_LIVE_API_KEY = os.getenv("ALPACA_LIVE_API_KEY")
ALPACA_LIVE_SECRET = os.getenv("ALPACA_LIVE_SECRET")
ALPACA_LIVE_TRADING_REST_ENDPOINT = "https://api.alpaca.markets"

ALPACA_WEBSOCKET_ENDPOINT = "wss://data.alpaca.markets/stream"
ALPACA_DATA_REST_ENDPOINT = "https://data.alpaca.markets/v1"

# Market Stack
MARKETSTACK_FREE_API_KEY = os.getenv("MARKETSTACK_FREE_API_KEY")

# Alpha Vantage
ALPHAVANTAGE_FREE_API_KEY_01 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_01")
ALPHAVANTAGE_FREE_API_KEY_02 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_02")
ALPHAVANTAGE_FREE_API_KEY_03 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_03")
ALPHAVANTAGE_FREE_API_KEY_04 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_04")
ALPHAVANTAGE_FREE_API_KEY_05 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_05")
ALPHAVANTAGE_FREE_API_KEY_06 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_06")
ALPHAVANTAGE_FREE_API_KEY_07 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_07")
ALPHAVANTAGE_FREE_API_KEY_08 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_08")
ALPHAVANTAGE_FREE_API_KEY_09 = os.getenv("ALPHAVANTAGE_FREE_API_KEY_09")

# Polygon
POLYGON_API_KEY = ALPACA_LIVE_API_KEY

# Tiingo marked data API
TIINGO_API_KEY = os.getenv("TIINGO_API_KEY")

# Finnhub.io
FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY")
